# Generated by Django 4.2.27 on 2026-02-04 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Сумма в рублях')),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('provider', models.CharField(default='mock', help_text='Провайдер платежа', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('success', 'Успешно'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('external_payment_id', models.CharField(blank=True, help_text='ID платежа у провайдера', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, help_text='None для FREE', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['price_rub']},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='code',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='conversions_per_day',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='is_guest_plan',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='max_file_size_mb',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='max_video_seconds',
        ),
        migrations.AddField(
            model_name='plan',
            name='duration_days',
            field=models.IntegerField(default=0, help_text='Длительность в днях (0 для FREE)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='limits',
            field=models.JSONField(default=dict, help_text='Лимиты: conversions_per_day, max_file_size_mb, available_formats'),
        ),
        migrations.AddField(
            model_name='plan',
            name='price_rub',
            field=models.IntegerField(default=0, help_text='Цена в рублях'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro')], max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='userplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_plans', to='plans.plan'),
        ),
        migrations.AddField(
            model_name='userplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='plans.plan'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userplan',
            index=models.Index(fields=['user', 'is_active'], name='plans_userp_user_id_a87e57_idx'),
        ),
        migrations.AddIndex(
            model_name='userplan',
            index=models.Index(fields=['expires_at'], name='plans_userp_expires_8eb2c2_idx'),
        ),
    ]
